---
kind: pipeline
type: docker
name: test


workspace:
  path: /myproject

steps:
- name: build
  image: node:lts
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - apt update -y
  - apt install apt-transport-https ca-certificates curl software-properties-common -y
  - -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - apt-cache policy docker-ce
  - apt install docker-ce -y
  - echo $PASSWORD | docker login -u $USERNAME --password-stdin
  - cd client
  - docker build -t react-app .
  - docker tag react-app aabhusan/react-app:latest
  - docker push aabhusan/react-app:latest

  - cd ../server
  - docker build -t node-app .
  - docker tag node-app aabhusan/node-app:latest
  - docker push aabhusan/node-app:latest
