---
kind: pipeline
type: docker
name: test


workspace:
  path: /myproject


steps:
- name: react-app
  image: plugins/docker
  settings:
    repo: aabhusan/react-app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  dockerfile: /myproject/client/Dockerfile

- name: node-app
  image: plugins/docker
  settings:
    repo: aabhusan/node-app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  dockerfile: /myproject/server/Dockerfile
